/**
 * Enums adicionales
 * Enumeraciones para módulos como reglas de precio, ajustes, incidencias, etc.
 */

// Additional Cost Enums
export enum RequestType {
    TRANSPORT = 'TRANSPORT',
    TOLL = 'TOLL',
    FUEL = 'FUEL',
    MEALS = 'MEALS',
    LODGING = 'LODGING',
    WAITING_TIME = 'WAITING_TIME',
    ELECTRIC_VEHICLE_CHARGING_TIME = 'ELECTRIC_VEHICLE_CHARGING_TIME',
    OTHER = 'OTHER'
}

export enum RequestStatus {
    NEW = 'NEW',
    PENDING_TICKET_UPLOAD = 'PENDING_TICKET_UPLOAD',
    PENDING_VALIDATION = 'PENDING_VALIDATION',
    VALIDATED = 'VALIDATED',
    REQUEST_REJECTED = 'REQUEST_REJECTED',
    TICKET_REJECTED = 'TICKET_REJECTED'
}

export enum PricingType {
    FIXED = 'FIXED',
    PER_KM = 'PER_KM'
}

export enum AdjustmentType {
    BONUS = 'BONUS',
    PENALTY = 'PENALTY'
}

// Adjustment Reason Types
export enum ReasonType {
    MISSING_DOCUMENT = 'MISSING_DOCUMENT',
    FINE_MANAGEMENT = 'FINE_MANAGEMENT',
    ACCIDENT_MANAGEMENT = 'ACCIDENT_MANAGEMENT',
    ADDITIONAL_SERVICE = 'ADDITIONAL_SERVICE',
    INAPPROPRIATE_BEHAVIOR = 'INAPPROPRIATE_BEHAVIOR',
    UNPROFESSIONAL_DRESS = 'UNPROFESSIONAL_DRESS',
    NOT_RESPECT_PROCESS = 'NOT_RESPECT_PROCESS',
    PUNCTUALITY_LESS_4H = 'PUNCTUALITY_LESS_4H',
    PUNCTUALITY_MORE_4H = 'PUNCTUALITY_MORE_4H',
    PUNCTUALITY_MORE_1D = 'PUNCTUALITY_MORE_1D',
    FALSE_JUSTIFICATIONS = 'FALSE_JUSTIFICATIONS',
    SERVICE_NOT_COMPLETED = 'SERVICE_NOT_COMPLETED',
    SERVICE_NOT_CERTIFIED = 'SERVICE_NOT_CERTIFIED',
    OTHER = 'OTHER'
}

// Invoice Enums (exacto de Python)
export enum InvoiceStatus {
    PENDING_DRIVER = 'PENDING_DRIVER',
    PENDING_PAYMENT = 'PENDING_PAYMENT',
    PAID = 'PAID'
}

// Anomaly Enums
export enum AnomalyType {
    SCRATCH = 'SCRATCH',
    DENT = 'DENT',
    BREAK = 'BREAK',
    CHIP = 'CHIP',
    MISSING_ITEM = 'MISSING_ITEM',
    POOR_CONDITION = 'POOR_CONDITION',
    DIRTY = 'DIRTY',
    DESCRIPTION = 'DESCRIPTION'
}

export enum AnomalyCategory {
    BODYWORK = 'BODYWORK',
    GLASS = 'GLASS',
    INTERIOR = 'INTERIOR',
    OTHER = 'OTHER'
}

// Incidence Enums
export enum IncidenceType {
    ALL = 'ALL',
    PUNCTUALITY = 'PUNCTUALITY',
    EXCESS_KILOMETERS = 'EXCESS_KILOMETERS',
    INVENTORY_MISSING = 'INVENTORY_MISSING',
    INVENTORY_INCOMPLETE = 'INVENTORY_INCOMPLETE',
    DRIVER_BEHAVIOR = 'DRIVER_BEHAVIOR',
    DRIVER_APPEARANCE = 'DRIVER_APPEARANCE',
    DRIVER_CONGRATULATIONS = 'DRIVER_CONGRATULATIONS',
    OTHER = 'OTHER',
    DOCUMENT_MISSING = 'DOCUMENT_MISSING',
    DOCUMENT_BLURRED = 'DOCUMENT_BLURRED',
    DOCUMENT_INCOMPLETE = 'DOCUMENT_INCOMPLETE',
    DOCUMENT_INCORRECT = 'DOCUMENT_INCORRECT',
    CLIENT_PROTOCOL_FUEL = 'CLIENT_PROTOCOL_FUEL',
    CLIENT_PROTOCOL_CUSTOMER_CONTACT = 'CLIENT_PROTOCOL_CUSTOMER_CONTACT',
    CLIENT_PROTOCOL_SC_ADDITIONAL_SERVICE = 'CLIENT_PROTOCOL_SC_ADDITIONAL_SERVICE',
    CLIENT_PROTOCOL_SC_WASH = 'CLIENT_PROTOCOL_SC_WASH',
    CLIENT_PROTOCOL_SC_VEHICLE_PRESENTATION = 'CLIENT_PROTOCOL_SC_VEHICLE_PRESENTATION',
    CLIENT_PROTOCOL_OTHER = 'CLIENT_PROTOCOL_OTHER',
    INCIDENCE_OTHER_OR_MULTIPLE = 'INCIDENCE_OTHER_OR_MULTIPLE',
    INCIDENCE_THEFT_SUSPICION = 'INCIDENCE_THEFT_SUSPICION',
    INCIDENCE_BODYWORK_DAMAGE = 'INCIDENCE_BODYWORK_DAMAGE',
    INCIDENCE_GLASS_BREAKAGE = 'INCIDENCE_GLASS_BREAKAGE',
    INCIDENCE_FLAT_TIRE = 'INCIDENCE_FLAT_TIRE',
    INCIDENCE_WRONG_FUEL = 'INCIDENCE_WRONG_FUEL',
    INCIDENCE_INTERIOR_DAMAGE = 'INCIDENCE_INTERIOR_DAMAGE',
    FINE_OVERSPEED = 'FINE_OVERSPEED',
    FINE_TOLL = 'FINE_TOLL',
    FINE_UNPAID_PARKING = 'FINE_UNPAID_PARKING',
    FINE_OTHER = 'FINE_OTHER',
    FINE_TRAFFIC_CODE = 'FINE_TRAFFIC_CODE',
    BILLING_FAKE_RECEIPTS = 'BILLING_FAKE_RECEIPTS',
    INTERNAL_PROTOCOL_EMERGENCY_CONTACT = 'INTERNAL_PROTOCOL_EMERGENCY_CONTACT',
    INTERNAL_PROTOCOL_WARNING_NOTE = 'INTERNAL_PROTOCOL_WARNING_NOTE',
    INTERNAL_PROTOCOL_30_MIN_WAIT = 'INTERNAL_PROTOCOL_30_MIN_WAIT',
    INTERNAL_PROTOCOL_UNREPORTED_CHANGES = 'INTERNAL_PROTOCOL_UNREPORTED_CHANGES',
    INTERNAL_PROTOCOL_MISSION_NOT_COMPLETED = 'INTERNAL_PROTOCOL_MISSION_NOT_COMPLETED',
    INTERNAL_PROTOCOL_OTHER = 'INTERNAL_PROTOCOL_OTHER'
}

export enum IncidenceCreator {
    ADMIN = 'ADMIN',
    CLIENT = 'CLIENT'
}

export enum IncidenceStatus {
    NEW = 'NEW',
    PENDING_DRIVER = 'PENDING_DRIVER',
    PENDING_CLIENT = 'PENDING_CLIENT',
    PENDING_END_CUSTOMER = 'PENDING_END_CUSTOMER',
    PENDING_INTERNAL_COLLABORATOR = 'PENDING_INTERNAL_COLLABORATOR',
    PENDING_WORKSHOP = 'PENDING_WORKSHOP',
    PENDING_INSURANCE = 'PENDING_INSURANCE',
    FINISHED = 'FINISHED'
}

export enum Severity {
    NONE = 'NONE',
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH'
}

export enum Responsibility {
    DRIVER = 'DRIVER',
    FORCE_MAJEURE = 'FORCE_MAJEURE',
    CLIENT = 'CLIENT',
    END_CLIENT = 'END_CLIENT',
    INTERNAL_PROCESS = 'INTERNAL_PROCESS',
    DUPLICATE = 'DUPLICATE',
    TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
    NOT_APPLICABLE = 'NOT_APPLICABLE',
    THIRD_PARTY = 'THIRD_PARTY'
}

// Protocol Enums
export enum ProtocolType {
    SINGLE_CHECK = 'SINGLE_CHECK',
    MULTI_CHECK = 'MULTI_CHECK',
    IMAGE = 'IMAGE'
}

export enum DirectionType {
    ARRIVAL = 'ARRIVAL',
    DEPARTURE = 'DEPARTURE',
    BOTH = 'BOTH'
}

// Event Enums
export enum TransportEventType {
    CREATED = 'CREATED',
    UPDATED = 'UPDATED',
    DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
    DRIVER_CHANGED = 'DRIVER_CHANGED',
    CLIENT_CANCELED = 'CLIENT_CANCELED',
    DRIVER_CANCELED = 'DRIVER_CANCELED',
    CLIENT_APPT_SELECTED = 'CLIENT_APPT_SELECTED',
    DRIVER_DATETIME_SET = 'DRIVER_DATETIME_SET',
    PICKUP_DONE = 'PICKUP_DONE',
    DOC_START_UPLOADED = 'DOC_START_UPLOADED',
    DOC_END_UPLOADED = 'DOC_END_UPLOADED',
    EXPENSE_TICKET_UPL = 'EXPENSE_TICKET_UPL',
    DELIVERY_DONE = 'DELIVERY_DONE',
    MISSION_FINISHED = 'MISSION_FINISHED'
}

export enum DriverEventType {
    ONBOARD_REGISTERED = 'ONBOARD_REGISTERED',
    DOC_UPLOADED = 'DOC_UPLOADED',
    DOC_VALIDATED = 'DOC_VALIDATED',
    DOC_REJECTED = 'DOC_REJECTED',
    PROFILE_UPDATED = 'PROFILE_UPDATED',
    QUOTE_SENT = 'QUOTE_SENT',
    QUOTE_REJECTED = 'QUOTE_REJECTED',
    TRANSPORT_ASSIGNED = 'TRANSPORT_ASSIGNED',
    EXTRA_EXPENSE_REQUESTED = 'EXTRA_EXPENSE_REQUESTED',
    EXTRA_EXPENSE_ACCEPTED = 'EXTRA_EXPENSE_ACCEPTED',
    EXTRA_EXPENSE_REJECTED = 'EXTRA_EXPENSE_REJECTED',
    TICKET_UPLOADED = 'TICKET_UPLOADED',
    TICKET_ACCEPTED = 'TICKET_ACCEPTED',
    TICKET_REJECTED = 'TICKET_REJECTED',
    QUALITY_ISSUE_REPORTED = 'QUALITY_ISSUE_REPORTED'
}

export enum IncidenceEventType {
    OPENED = 'OPENED',
    COMMENT_ADDED = 'COMMENT_ADDED',
    STATUS_CHANGED = 'STATUS_CHANGED'
}

export enum DocumentType {
    FRONT_DNI = 'front_dni',
    BACK_DNI = 'back_dni',
    FRONT_DRIVING_LICENSE = 'front_driving_license',
    BACK_DRIVING_LICENSE = 'back_driving_license',
    SELF_EMPLOYMENT_REGISTRATION_FEE = 'self_employment_registration_fee',
    BANK_ACCOUNT_CERTIFICATE = 'bank_account_certificate',
    CRIMINAL_RECORD_CERTIFICATE = 'criminal_record_certificate',
    DRIVING_POINTS_CERTIFICATE = 'driving_points_certificate',
    SELF_EMPLOYMENT_PAYMENT_CERTIFICATE = 'self_employment_payment_certificate',
    TAX_CENSUS_REGISTRATION_CERTIFICATE = 'tax_census_registration_certificate',
    FORM_036 = 'form_036',
    RETA_REGISTRATION_RESOLUTION = 'reta_registration_resolution',
    SOCIAL_SECURITY_COMPLIANCE_CERTIFICATE = 'social_security_compliance_certificate',
    TAX_DEBT_CERTIFICATE = 'tax_debt_certificate',
    RESIDENCE_PERMIT_NIE = 'residence_permit_nie',
    WORK_PERMIT_NIE = 'work_permit_nie'
}

export enum IncidenceSeverity {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
    CRITICAL = 'CRITICAL'
}

export enum IncidenceStatus {
    OPEN = 'OPEN',
    IN_PROGRESS = 'IN_PROGRESS',
    RESOLVED = 'RESOLVED',
    CLOSED = 'CLOSED'
}

export enum CertificationStatus {
    PASSED = 'passed',
    REVOKED = 'revoked',
    MANUAL = 'manual'
}

// Exam Enums
export enum ExamQuestionType {
    SINGLE = 'single',
    MULTIPLE = 'multiple',
    TEXT = 'text',
    BOOLEAN = 'boolean'
}