/**
 * Enums de transporte
 * Enumeraciones relacionadas con transportes y logística
 */

export enum TransportPrincipalType {
    SIMPLE_MOVEMENT = 'SIMPLE_MOVEMENT',
    PICKUP_TO_FINAL_CUSTOMER = 'PICKUP_TO_FINAL_CUSTOMER',
    DELIVERY_TO_FINAL_CUSTOMER = 'DELIVERY_TO_FINAL_CUSTOMER',
    PICKUP_AND_DELIVERY_TO_FINAL_CUSTOMER = 'PICKUP_AND_DELIVERY_TO_FINAL_CUSTOMER',
    WITH_STOPOVER = 'WITH_STOPOVER'
}

export enum TransportStatus {
    PENDING = 'PENDING',
    PLANIFIED = 'PLANIFIED',
    IN_COURSE = 'IN_COURSE',
    FINISHED = 'FINISHED',
    CANCELLED = 'CANCELLED',
    DELETED = 'DELETED',
    EXPIRED = 'EXPIRED'
}

export enum CancelledReason {
    VEHICLE_NOT_AVAILABLE = 'VEHICLE_NOT_AVAILABLE',
    VEHICLE_NOT_READY_AT_DEPARTURE = 'VEHICLE_NOT_READY_AT_DEPARTURE',
    VEHICLE_NOT_WORKING = 'VEHICLE_NOT_WORKING',
    MISSING_MANDATORY_SAFETY_EQUIPMENT = 'MISSING_MANDATORY_SAFETY_EQUIPMENT',
    INCORRECT_LICENSE_PLATE = 'INCORRECT_LICENSE_PLATE',
    BREAKDOWN_DURING_TRANSPORT = 'BREAKDOWN_DURING_TRANSPORT',
    ACCIDENT_DURING_TRANSPORT = 'ACCIDENT_DURING_TRANSPORT',
    VEHICLE_REJECTED_AT_ARRIVAL = 'VEHICLE_REJECTED_AT_ARRIVAL',
    VEHICLE_REJECTED_NO_APPOINTMENT_AT_DEPOT = 'VEHICLE_REJECTED_NO_APPOINTMENT_AT_DEPOT',
    RETURN_REJECTED = 'RETURN_REJECTED',
    END_CUSTOMER_REQUEST = 'END_CUSTOMER_REQUEST',
    CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
    CANCELLATION_DUE_TO_DRIVER_RESERVATION_CANCELLED = 'CANCELLATION_DUE_TO_DRIVER_RESERVATION_CANCELLED',
    RETURN_CANCELLED_DUE_TO_OUTBOUND_CANCELLATION = 'RETURN_CANCELLED_DUE_TO_OUTBOUND_CANCELLATION',
    CONTACT_ABSENT_AT_DEPARTURE = 'CONTACT_ABSENT_AT_DEPARTURE',
    CONTACT_ABSENT_AT_ARRIVAL = 'CONTACT_ABSENT_AT_ARRIVAL',
    UNREACHABLE_CONTACT_AT_START = 'UNREACHABLE_CONTACT_AT_START',
    UNREACHABLE_CONTACT_AT_ARRIVAL = 'UNREACHABLE_CONTACT_AT_ARRIVAL',
    NO_APPOINTMENT_POSSIBLE_WITH_END_CUSTOMER = 'NO_APPOINTMENT_POSSIBLE_WITH_END_CUSTOMER',
    NO_APPOINTMENT_WITH_ARRIVAL_CONTACT = 'NO_APPOINTMENT_WITH_ARRIVAL_CONTACT',
    DUPLICATE = 'DUPLICATE',
    INCORRECT_PICKUP_ADDRESS = 'INCORRECT_PICKUP_ADDRESS',
    INCORRECT_DELIVERY_ADDRESS = 'INCORRECT_DELIVERY_ADDRESS',
    NON_COMPLIANT_TRANSPORT_REQUEST = 'NON_COMPLIANT_TRANSPORT_REQUEST',
    CANCELLATION_DUE_TO_CAPACITY = 'CANCELLATION_DUE_TO_CAPACITY',
    OTHER = 'OTHER'
}

export enum LegPointType {
    ORIGIN = 'ORIGIN',
    STOPOVER = 'STOPOVER',
    DESTINATION = 'DESTINATION'
}