import { TransportPrincipalType, TransportStatus } from '@enums/transport.enum';
import { TransportsRetrieveResponse } from '@dtos/transports/transports.dto';

export const transportsMockData: TransportsRetrieveResponse[] = [
  {
    id: 1,
    is_express: false,
    transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
    transport_type: 'Concesionario a Taller',
    phone: '+34611111111',
    has_ferry: true,
    appointment_management: true,
    emails: ['cliente1@example.com'],
    comment: 'Entrega estándar.',
    group_number: 1,
    reservation_number: 'R00001',
    reference_number: 'REF001',
    is_blocked: false,
    invoiced: false,
    duration: 2.5,
    transport_status: TransportStatus.PENDING,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: 8,
    driver_name: 'Diego',
    admin_id: 3,
    admin_name: 'Ana',
    tags: [9],
    legs: [
      {
        id: 1,
        order: 1,
        duration: 2.5,
        kilometers: '200.50',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-14T10:00:00+02:00'),
        expected_departure_to: new Date('2025-10-14T10:30:00+02:00'),
        expected_arrival_from: new Date('2025-10-14T12:00:00+02:00'),
        expected_arrival_to: new Date('2025-10-14T12:30:00+02:00'),
        origin_address: {
          id: 1,
          title: 'Concesionario Madrid Norte',
          longitude: -3.7038,
          latitude: 40.4168,
          country: 'España',
          city: 'Madrid',
          postal_code: '28001',
          province: 'Madrid',
          description: 'España, Madrid, 28001, Concesionario Madrid Norte',
          address_type: 'DEALERSHIP' as any,
          contact_name: 'Carlos López',
          contact_email: 'contacto@madridnorte.com',
          contact_phone: '+34910000001',
          transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 2,
          title: 'Taller Barcelona Sur',
          longitude: 2.1734,
          latitude: 41.3851,
          country: 'España',
          city: 'Barcelona',
          postal_code: '08001',
          province: 'Barcelona',
          description: 'España, Barcelona, 08001, Taller Barcelona Sur',
          address_type: 'REPAIR_SHOP' as any,
          contact_name: 'Marta García',
          contact_email: 'info@barcelonasur.com',
          contact_phone: '+34930000002',
          transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 1,
          license_plate: '1234ABC',
          brand: 'Toyota',
          model: 'Yaris',
          fuel_type: 'GASOLINE' as any,
          size: 'SMALL' as any,
          image: null,
          insurance_date_start: new Date('2025-01-10'),
          insurance_date_end: new Date('2026-01-10'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '200.50',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 1,
      license_plate: '1234ABC',
      brand: 'Toyota',
      model: 'Yaris',
      fuel_type: 'GASOLINE' as any,
      size: 'SMALL' as any,
      image: null,
      insurance_date_start: new Date('2025-01-10'),
      insurance_date_end: new Date('2026-01-10'),
      created_date: null,
      modified_date: null
    }
  },
  {
    id: 2,
    is_express: true,
    transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
    transport_type: null,
    phone: '+34622222222',
    has_ferry: false,
    appointment_management: false,
    emails: ['cliente2@example.com'],
    comment: 'Entrega urgente a cliente final.',
    group_number: 2,
    reservation_number: 'R00002',
    reference_number: 'REF002',
    is_blocked: false,
    invoiced: false,
    duration: 1.2,
    transport_status: TransportStatus.IN_COURSE,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: null,
    driver_name: null,
    admin_id: 3,
    admin_name: 'Ana',
    tags: [9, 10],
    legs: [
      {
        id: 2,
        order: 1,
        duration: 1.2,
        kilometers: '120.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-14T11:00:00+02:00'),
        expected_departure_to: new Date('2025-10-14T11:15:00+02:00'),
        expected_arrival_from: new Date('2025-10-14T12:00:00+02:00'),
        expected_arrival_to: new Date('2025-10-14T12:10:00+02:00'),
        origin_address: {
          id: 2,
          title: 'Taller Barcelona Sur',
          longitude: 2.1734,
          latitude: 41.3851,
          country: 'España',
          city: 'Barcelona',
          postal_code: '08001',
          province: 'Barcelona',
          description: 'España, Barcelona, 08001, Taller Barcelona Sur',
          address_type: 'REPAIR_SHOP' as any,
          contact_name: 'Marta García',
          contact_email: 'info@barcelonasur.com',
          contact_phone: '+34930000002',
          transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 3,
          title: 'Almacén Central Valencia',
          longitude: -0.3763,
          latitude: 39.4699,
          country: 'España',
          city: 'Valencia',
          postal_code: '46001',
          province: 'Valencia',
          description: 'España, Valencia, 46001, Almacén Central Valencia',
          address_type: 'WAREHOUSE' as any,
          contact_name: 'Andrés Pérez',
          contact_email: 'logistica@valencia.com',
          contact_phone: '+34960000003',
          transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-S 06:00-22:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 2,
          license_plate: '5678DEF',
          brand: 'Volkswagen',
          model: 'Golf',
          fuel_type: 'DIESEL' as any,
          size: 'MEDIUM' as any,
          image: null,
          insurance_date_start: new Date('2025-03-01'),
          insurance_date_end: new Date('2026-03-01'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '120.00',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 2,
      license_plate: '5678DEF',
      brand: 'Volkswagen',
      model: 'Golf',
      fuel_type: 'DIESEL' as any,
      size: 'MEDIUM' as any,
      image: null,
      insurance_date_start: new Date('2025-03-01'),
      insurance_date_end: new Date('2026-03-01'),
      created_date: null,
      modified_date: null
    }
  },
  {
    id: 3,
    is_express: false,
    transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
    transport_type: null,
    phone: '+34633333333',
    has_ferry: true,
    appointment_management: true,
    emails: ['cliente3@example.com'],
    comment: 'Con parada intermedia en Valencia.',
    group_number: 3,
    reservation_number: 'R00003',
    reference_number: 'REF003',
    is_blocked: false,
    invoiced: false,
    duration: 5.0,
    transport_status: TransportStatus.PLANIFIED,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: null,
    driver_name: null,
    admin_id: 3,
    admin_name: 'Ana',
    tags: [9],
    legs: [
      {
        id: 3,
        order: 1,
        duration: 5.0,
        kilometers: '450.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-14T09:00:00+02:00'),
        expected_departure_to: new Date('2025-10-14T09:30:00+02:00'),
        expected_arrival_from: new Date('2025-10-14T14:00:00+02:00'),
        expected_arrival_to: new Date('2025-10-14T14:15:00+02:00'),
        origin_address: {
          id: 1,
          title: 'Concesionario Madrid Norte',
          longitude: -3.7038,
          latitude: 40.4168,
          country: 'España',
          city: 'Madrid',
          postal_code: '28001',
          province: 'Madrid',
          description: 'España, Madrid, 28001, Concesionario Madrid Norte',
          address_type: 'DEALERSHIP' as any,
          contact_name: 'Carlos López',
          contact_email: 'contacto@madridnorte.com',
          contact_phone: '+34910000001',
          transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 3,
          title: 'Almacén Central Valencia',
          longitude: -0.3763,
          latitude: 39.4699,
          country: 'España',
          city: 'Valencia',
          postal_code: '46001',
          province: 'Valencia',
          description: 'España, Valencia, 46001, Almacén Central Valencia',
          address_type: 'WAREHOUSE' as any,
          contact_name: 'Andrés Pérez',
          contact_email: 'logistica@valencia.com',
          contact_phone: '+34960000003',
          transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-S 06:00-22:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 3,
          license_plate: '9012GHI',
          brand: 'Hyundai',
          model: 'Ioniq',
          fuel_type: 'HYBRID' as any,
          size: 'MEDIUM' as any,
          image: null,
          insurance_date_start: new Date('2024-11-15'),
          insurance_date_end: new Date('2025-11-15'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '450.00',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 3,
      license_plate: '9012GHI',
      brand: 'Hyundai',
      model: 'Ioniq',
      fuel_type: 'HYBRID' as any,
      size: 'MEDIUM' as any,
      image: null,
      insurance_date_start: new Date('2024-11-15'),
      insurance_date_end: new Date('2025-11-15'),
      created_date: null,
      modified_date: null
    }
  },
  {
    id: 4,
    is_express: false,
    transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
    transport_type: 'Concesionario a ITV',
    phone: '+34644444444',
    has_ferry: false,
    appointment_management: true,
    emails: ['cliente4@example.com'],
    comment: 'Entrega desde Madrid Norte a Alcobendas (mismo origen que T1).',
    group_number: 4,
    reservation_number: 'R00004',
    reference_number: 'REF004',
    is_blocked: false,
    invoiced: false,
    duration: 0.5,
    transport_status: TransportStatus.PLANIFIED,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: null,
    driver_name: null,
    admin_id: 3,
    admin_name: 'Ana',
    tags: [9],
    legs: [
      {
        id: 4,
        order: 1,
        duration: 0.5,
        kilometers: '15.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-15T10:00:00+02:00'),
        expected_departure_to: new Date('2025-10-15T10:10:00+02:00'),
        expected_arrival_from: new Date('2025-10-15T10:20:00+02:00'),
        expected_arrival_to: new Date('2025-10-15T10:30:00+02:00'),
        origin_address: {
          id: 1,
          title: 'Concesionario Madrid Norte',
          longitude: -3.7038,
          latitude: 40.4168,
          country: 'España',
          city: 'Madrid',
          postal_code: '28001',
          province: 'Madrid',
          description: 'España, Madrid, 28001, Concesionario Madrid Norte',
          address_type: 'DEALERSHIP' as any,
          contact_name: 'Carlos López',
          contact_email: 'contacto@madridnorte.com',
          contact_phone: '+34910000001',
          transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 4,
          title: 'ITV Alcobendas',
          longitude: -3.638,
          latitude: 40.547,
          country: 'España',
          city: 'Madrid',
          postal_code: '28100',
          province: 'Madrid',
          description: 'España, Madrid, 28100, ITV Alcobendas',
          address_type: 'ITV' as any,
          contact_name: 'Lucía Martín',
          contact_email: 'info@itvalcobendas.es',
          contact_phone: '+34910000004',
          transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-D 07:00-15:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 4,
          license_plate: '3456JKL',
          brand: 'Renault',
          model: 'ZOE',
          fuel_type: 'ELECTRIC' as any,
          size: 'SMALL' as any,
          image: null,
          insurance_date_start: new Date('2025-02-01'),
          insurance_date_end: new Date('2026-02-01'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '15.00',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 4,
      license_plate: '3456JKL',
      brand: 'Renault',
      model: 'ZOE',
      fuel_type: 'ELECTRIC' as any,
      size: 'SMALL' as any,
      image: null,
      insurance_date_start: new Date('2025-02-01'),
      insurance_date_end: new Date('2026-02-01'),
      created_date: null,
      modified_date: null
    }
  },
  {
    id: 5,
    is_express: false,
    transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
    transport_type: null,
    phone: '+34655555555',
    has_ferry: false,
    appointment_management: true,
    emails: ['cliente5@example.com'],
    comment: 'Transporte con parada en Valencia antes de llegar a Barcelona.',
    group_number: 5,
    reservation_number: 'R00005',
    reference_number: 'REF005',
    is_blocked: false,
    invoiced: false,
    duration: 4.0,
    transport_status: TransportStatus.PLANIFIED,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: null,
    driver_name: null,
    admin_id: 3,
    admin_name: 'Ana',
    tags: [9, 10, 11],
    legs: [
      {
        id: 5,
        order: 1,
        duration: 1.8,
        kilometers: '175.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-15T09:30:00+02:00'),
        expected_departure_to: new Date('2025-10-15T09:45:00+02:00'),
        expected_arrival_from: new Date('2025-10-15T11:00:00+02:00'),
        expected_arrival_to: new Date('2025-10-15T11:15:00+02:00'),
        origin_address: {
          id: 1,
          title: 'Concesionario Madrid Norte',
          longitude: -3.7038,
          latitude: 40.4168,
          country: 'España',
          city: 'Madrid',
          postal_code: '28001',
          province: 'Madrid',
          description: 'España, Madrid, 28001, Concesionario Madrid Norte',
          address_type: 'DEALERSHIP' as any,
          contact_name: 'Carlos López',
          contact_email: 'contacto@madridnorte.com',
          contact_phone: '+34910000001',
          transport_principal_type: TransportPrincipalType.SIMPLE_MOVEMENT,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 3,
          title: 'Almacén Central Valencia',
          longitude: -0.3763,
          latitude: 39.4699,
          country: 'España',
          city: 'Valencia',
          postal_code: '46001',
          province: 'Valencia',
          description: 'España, Valencia, 46001, Almacén Central Valencia',
          address_type: 'WAREHOUSE' as any,
          contact_name: 'Andrés Pérez',
          contact_email: 'logistica@valencia.com',
          contact_phone: '+34960000003',
          transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-S 06:00-22:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'STOPOVER',
        vehicle: {
          id: 5,
          license_plate: '7890MNO',
          brand: 'Volvo',
          model: 'XC60 Recharge',
          fuel_type: 'PLUG_IN_HYBRID' as any,
          size: 'LARGE' as any,
          image: null,
          insurance_date_start: new Date('2024-09-10'),
          insurance_date_end: new Date('2025-09-10'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      },
      {
        id: 6,
        order: 2,
        duration: 2.5,
        kilometers: '175.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-15T11:15:00+02:00'),
        expected_departure_to: new Date('2025-10-15T11:30:00+02:00'),
        expected_arrival_from: new Date('2025-10-15T13:30:00+02:00'),
        expected_arrival_to: new Date('2025-10-15T13:45:00+02:00'),
        origin_address: {
          id: 3,
          title: 'Almacén Central Valencia',
          longitude: -0.3763,
          latitude: 39.4699,
          country: 'España',
          city: 'Valencia',
          postal_code: '46001',
          province: 'Valencia',
          description: 'España, Valencia, 46001, Almacén Central Valencia',
          address_type: 'WAREHOUSE' as any,
          contact_name: 'Andrés Pérez',
          contact_email: 'logistica@valencia.com',
          contact_phone: '+34960000003',
          transport_principal_type: TransportPrincipalType.WITH_STOPOVER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-S 06:00-22:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 2,
          title: 'Taller Barcelona Sur',
          longitude: 2.1734,
          latitude: 41.3851,
          country: 'España',
          city: 'Barcelona',
          postal_code: '08001',
          province: 'Barcelona',
          description: 'España, Barcelona, 08001, Taller Barcelona Sur',
          address_type: 'REPAIR_SHOP' as any,
          contact_name: 'Marta García',
          contact_email: 'info@barcelonasur.com',
          contact_phone: '+34930000002',
          transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 5,
          license_plate: '7890MNO',
          brand: 'Volvo',
          model: 'XC60 Recharge',
          fuel_type: 'PLUG_IN_HYBRID' as any,
          size: 'LARGE' as any,
          image: null,
          insurance_date_start: new Date('2024-09-10'),
          insurance_date_end: new Date('2025-09-10'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '350.00',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 5,
      license_plate: '7890MNO',
      brand: 'Volvo',
      model: 'XC60 Recharge',
      fuel_type: 'PLUG_IN_HYBRID' as any,
      size: 'LARGE' as any,
      image: null,
      insurance_date_start: new Date('2024-09-10'),
      insurance_date_end: new Date('2025-09-10'),
      created_date: null,
      modified_date: null
    }
  },
  {
    id: 6,
    is_express: true,
    transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
    transport_type: null,
    phone: '+34666666666',
    has_ferry: false,
    appointment_management: false,
    emails: ['cliente6@example.com'],
    comment: 'Empieza donde termina el T1 (Barcelona Sur).',
    group_number: 6,
    reservation_number: 'R00006',
    reference_number: 'REF006',
    is_blocked: false,
    invoiced: false,
    duration: 3.0,
    transport_status: TransportStatus.PLANIFIED,
    cancelled_comment: '',
    cancelled_reason: null,
    client_id: 1,
    client_name: 'Audi España',
    driver_id: null,
    driver_name: null,
    admin_id: 3,
    admin_name: 'Ana',
    tags: [13],
    legs: [
      {
        id: 7,
        order: 1,
        duration: 3.0,
        kilometers: '280.00',
        has_ferry: false,
        expected_departure_from: new Date('2025-10-15T13:00:00+02:00'),
        expected_departure_to: new Date('2025-10-15T13:10:00+02:00'),
        expected_arrival_from: new Date('2025-10-15T16:00:00+02:00'),
        expected_arrival_to: new Date('2025-10-15T16:15:00+02:00'),
        origin_address: {
          id: 2,
          title: 'Taller Barcelona Sur',
          longitude: 2.1734,
          latitude: 41.3851,
          country: 'España',
          city: 'Barcelona',
          postal_code: '08001',
          province: 'Barcelona',
          description: 'España, Barcelona, 08001, Taller Barcelona Sur',
          address_type: 'REPAIR_SHOP' as any,
          contact_name: 'Marta García',
          contact_email: 'info@barcelonasur.com',
          contact_phone: '+34930000002',
          transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        destination_address: {
          id: 5,
          title: 'Concesionario Valencia Este',
          longitude: -0.35,
          latitude: 39.47,
          country: 'España',
          city: 'Valencia',
          postal_code: '46020',
          province: 'Valencia',
          description: 'España, Valencia, 46020, Concesionario Valencia Este',
          address_type: 'DEALERSHIP' as any,
          contact_name: 'Ana Torres',
          contact_email: 'ana@valenciaeste.es',
          contact_phone: '+34960000005',
          transport_principal_type: TransportPrincipalType.DELIVERY_TO_FINAL_CUSTOMER,
          client_name: 'Audi España',
          subentity: '',
          subentity_name: '',
          opening_hours: [],
          opening_hours_summary: 'L-V 08:00-14:00 / 15:00-19:00',
          created_date: null,
          modified_date: null
        },
        connection_type: 'DESTINATION',
        vehicle: {
          id: 6,
          license_plate: '1111PQR',
          brand: 'Seat',
          model: 'Arona TGI',
          fuel_type: 'LPG' as any,
          size: 'MEDIUM' as any,
          image: null,
          insurance_date_start: new Date('2025-05-20'),
          insurance_date_end: new Date('2026-05-20'),
          created_date: null,
          modified_date: null
        },
        documents: [],
        additional_services: []
      }
    ],
    kilometers: '280.00',
    created_date: null,
    modified_date: null,
    show_timeline: false,
    timeline: null,
    countries: ['España'],
    additional_services: [],
    vehicle: {
      id: 6,
      license_plate: '1111PQR',
      brand: 'Seat',
      model: 'Arona TGI',
      fuel_type: 'LPG' as any,
      size: 'MEDIUM' as any,
      image: null,
      insurance_date_start: new Date('2025-05-20'),
      insurance_date_end: new Date('2026-05-20'),
      created_date: null,
      modified_date: null
    }
  }
];

